name: Deploy
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Download modules
        run: |
          go get ./...

      - name: Run tests
        run: |
          go test -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: docker build .
