name: Go
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setting up
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Go get
        run: |
          go get ./...

      - name: Test
        run: |
          go test -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: docker build .
